# Generated by Django 3.2.5 on 2021-08-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('userId', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('added', models.DateTimeField()),
                ('lastAccessed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.IntegerField()),
                ('childId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Items',
            fields=[
                ('itemId', models.IntegerField()),
                ('SubItemId', models.IntegerField(primary_key=True, serialize=False)),
                ('characterization', models.CharField(max_length=120)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Lookup',
            fields=[
                ('itemId', models.IntegerField()),
                ('tagId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.IntegerField()),
                ('tag', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('authToken', models.CharField(max_length=120)),
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('signUp', models.DateTimeField()),
                ('lastLogin', models.DateTimeField()),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.items')),
                ('parentID', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('categoryTypeCode', models.CharField(max_length=10)),
            ],
            bases=('todo.items',),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.items')),
                ('typeCode', models.CharField(max_length=120)),
            ],
            bases=('todo.items',),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.items')),
                ('parentID', models.IntegerField()),
                ('deadling', models.DateTimeField()),
                ('categoryTypeCode', models.CharField(max_length=10)),
            ],
            bases=('todo.items',),
        ),
    ]
