# Generated by Django 3.2.5 on 2021-08-02 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_actions_categories_items_projectchildren_projects_sub_items_tag_lookup_tags_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectChildren',
            new_name='Project_Children',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='deadling',
        ),
        migrations.RemoveField(
            model_name='sub_items',
            name='SubItemId',
        ),
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.CharField(default='typeless', max_length=120),
        ),
        migrations.AddField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sub_items',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actions',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='categories',
            name='items_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='todo.items'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='typeCode',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='lastAccessed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tag_lookup',
            name='tagId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='signUp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
